lib/install.js, lib/utils.js, test/sameMaxRange.test.js
chair 这种规模可以少100多次对 npm registry 的请求
=> feat: cache by range max bound

bin/install.js, test/fixtures/auto-set-npm-env/postinstall.js, test/postinstall.test.js
`--foo=bar` => `npm_config_foo: bar`
=> fix: --foo=bar should use `npm_config_` env prefix name

bin/install.js, lib/index.js
ignore not range version check
=> fix: install package@tag -g should work

lib/get.js, lib/install.js
=> fix: try to fix the max satisfy version (n.x) in grandfather's deps

README.md, bin/install.js, lib/local_install.js, lib/preinstall.js, test/fixtures/ignore-scripts/package.json, test/fixtures/ignore-scripts/pkg/index.js, test/fixtures/ignore-scripts/pkg/package.json, test/ignoreScripts.test.js
=> feat: support ignore-scripts

lib/get.js, lib/local_install.js, package.json
\- - 121.0.29.221 [01/Apr/2016:14:53:48 +0800] "GET /ms/download/ms-0.7.1.tgz HTTP/1.1" 302 5 "install koa should --production --uuid=7d5ac1b0-f7d6-11e5-b5fa-172edeb64a6a" "npminstall/1.5.3 node-urllib/2.7.3 Node.js/4.4.1 (OS X El Capitan; x64)" 0.007 0.007
121.0.29.221 - 100.97.90.133 [01/Apr/2016:14:53:27 +0800] "GET /lodash.keys/%3E%3D3.1.2%20%3C4.0.0 HTTP/1.0" 200 2376 "install less-loader antd react react-dom mocha grunt-mocha-test --uuid=6f138380-f7d6-11e5-b5fa-172edeb64a6a" "npminstall/1.5.3 node-urllib/2.7.3 Node.js/4.4.1 (OS X El Capitan; x64)" 0.030 0.029
closes #66
=> feat: add referer for registry access log

lib/utils.js, test/bin.test.js
- issue reference of https://github.com/cnpm/cnpm/issues/112
test:
```javascript
mocha -r thunk-mocha -t 120000 test/bin.test.js   # passed 
```
=> fix: utils.forceSymlink precheck dest dir exists

bin/install.js, test/installGlobal.test.js
```bash
npminstall -g foo --prefix=/tmp/path
```
=> feat: support global install prefix argv

bin/install.js, package.json
closes https://github.com/cnpm/npminstall/issues/145
=> fix: global prefix support `~/foo/path`

lib/download/git.js, lib/download/local.js, lib/download/remote.js, package.json
Hi there,
This week a new version of the [uuid](https://github.com/kelektiv/node-uuid) module got released. The old module which was available by the name [node-uuid](https://www.npmjs.com/package/node-uuid) got deprecated and will show error message upon every install of the module.
To get rid of those install errors I've created this **automated pull request**. I've run some checks against your code base to test whether you're using one of the [deprecated apis](https://github.com/kelektiv/node-uuid/commit/5ae7287fc935eb55ef39133e4be17ef623ca000e), but this isn't the case.
Please test the changes against your code. I didn't run any tests and therefore can't guarantee that it isn't breaking. You can also just close this pr if you don't want to update your module.
In case there's already …
=> Update uuid to version 3.0.0

bin/install.js, bin/update.js, test/update.test.js
closes https://github.com/cnpm/npminstall/issues/181
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/182)
=> fix: update cli should ignore package names args

lib/bin.js, lib/install.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/191)
=> fix: should limit sub package install parallel

lib/dependencies.js, lib/install.js, lib/local_install.js, test/fixtures/try-to-use-one-version/package.json, test/use-exists-version.test.js
closes https://github.com/cnpm/npminstall/issues/192
=> fix: get max satisfy version from root dependencies instead of *

README.md, bin/install.js, lib/download/npm.js, lib/install.js, lib/local_install.js, package.json, test/fixtures/flatten/mod1/package.json, test/fixtures/flatten/mod2/package.json, test/fixtures/flatten/mod3/package.json, test/fixtures/flatten/mod4/package.json, test/flatten.test.js, test/use-exists-version.test.js
两种不同的选择：
1. 完全遵循 semver 原则，各个模块独立安装自身依赖。（有利于 node 运行环境，不需要考虑体积问题）
2. 在遵循 semver 的原则下，尽可能合并模块版本。（有利于前端）
> the ~ prefix says "match any patch version greater than or equal to the one I specified"
按照上面 [npm 的人对 semver 的解释](https://github.com/npm/npm/issues/11887#issuecomment-201615642)，`~1.1.0` 并不保证一定安装到符合这个规则的最新版本。但是一定是使用到符合这条规则的版本。
npm 的安装策略如下：
```sh
root/
koa@1.1.0
mod/
koa@~1.1.0
root/
koa@1.1.0
mod/
koa@^1.1.0
root/
koa@~1.1.0
mod/
koa@^1.1.0
root/
mod/
koa@^1.1.0
moe/
koa@~1.1.0
```
在一些项目上测试了一下，egg 和 antd 都没有遇到这个问题，一般就是 babel 那些可能遇到，但是影响不到，所以需要加 `--flatten` 的 flag 来开启 2，默认都是走 1 的方式，之前的 hack 都去掉了。
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/197)
=> feat: lookup ancestor's dependencies

.travis.yml, appveyor.yml, lib/patch_buffer.js, lib/utils.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/247)
=> fix: make sure Buffer.alloc exit on node < 4.5.0

bin/install.js, lib/download/npm.js, lib/utils.js, test/fix-bug-versions.test.js, test/fixtures/fix-bug-versions-app/package.json
use `--fix-bug-versions` to enable this feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/256)
=> feat: support auto fix bug version of package

README.md, bin/install.js, lib/dependencies.js, lib/install.js, lib/local_install.js, test/all.js, test/dependencies.test.js, test/fixtures/ignore-optional/package.json, test/fixtures/local-install-pkgs/package.json, test/index.test.js, test/install-ignore-optional.test.js, test/local-install-pkgs.test.js
Don’t install optional dependencies.
like yarn does: https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-optional
=> feat: support --no-optional on install process

bin/install.js, lib/download/npm.js, lib/format_install_options.js, lib/install.js, lib/local_install.js, test/dependencies-tree.test.js, test/fixtures/dependencies-tree/.dependencies_tree.json, test/fixtures/dependencies-tree/package.json
1. 通过 `--save-dependencies-tree` 开启依赖树生成，生成的依赖树位于 `node_modules/.dependencies_tree.json`
2. 通过 `--dependencies-tree=.dependencies_tree.json` 来指定从生成的依赖树恢复
注意：只会保存 npm resolve 的依赖树，从远程地址或者 git 仓库拉下来的没有 semver，也不会保存下来，生成的依赖树文件在 1~5MB 左右，所以生成保存后打包时要清理掉。
/cc @coolme200
=> feat: support dependencies tree

lib/local_install.js, test/seperate-dependencies.test.js
production 可能是环境变量设置，如果手动指定了 `--client`，优先级更高
=> fix: --client override --prodcution

lib/cnpm_config.js, lib/get.js, test/fixtures/auth/.cnpmrc, test/get.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/259)
=> feat: support authorization

package.json, test/bundleDependencies.test.js, test/fixtures/runscript-with-mocha/package.json, test/runscript-with-mocha.test.js, test/uninstallGlobal.test.js
Work around quoted batch file names
fixed https://github.com/npm/cmd-shim/issues/10
=> deps: cmd-shim v3

lib/bin.js, package.json, test/all.js, test/bigPackage.test.js, test/bundleDependencies.test.js, test/concurrency-install.test.js, test/installScopeRegistry.test.js, test/proxy.test.js, test/uninstallGlobal.test.js
pick from https://github.com/cnpm/npminstall/pull/317
=> fix: dont add quotes on node global bin path on Windows

lib/format_install_options.js, test/fixtures/install-husky-4/index.js, test/fixtures/install-husky-4/package.json, test/install-with-env.test.js
closes https://github.com/cnpm/cnpm/issues/317
=> feat: support INIT_CWD env

lib/utils.js
避免由于值变化造成每次安装后的 package.json 文件不一致
=> fix: fixed npminstall_done label

lib/download/local.js, test/ignoreScripts.test.js, test/installLocal.test.js
之前的目录中可能有 node_modules 等不需要的文件，通过 npm pack 来打包，如果没有 npm，fallback 到直接 copy
=> fix: install local folder use npm pack

bin/install.js, test/install-cache-strict.test.js
```bash
npm_config_cache=/oss/cache/.npminstall npminstall koa
```
=> feat: support npm_config_cache to change default cache dir (#335)

lib/local_install.js
tnpm 走内部服务端生成依赖安装 node_modules，需要执行 postinstall，这里直接服用 npminstall 的实现。
=> chore: exports local_install/runPostInstallTasks function

lib/local_install.js
fixed:[#363 ](https://github.com/cnpm/npminstall/issues/363)
fixed the error that can't use by npminstall({options}) on version '^5.0.0'
=> fixed:#363

lib/format_install_options.js, package.json
https://security.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908
Detailed paths
Introduced through: npminstall@5.2.2 › ora@3.4.0 › strip-ansi@5.2.0 › ansi-regex@4.1.0
Remediation: Upgrade to ora@4.0.3.
=> deps: upgrade ora@5 for security

bin/install.js, test/custom-registry.test.js
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received an instance of Array
=> fix: npminstall multi-registry options

lib/download/npm.js, lib/utils.js, test/utils.test.js
closes https://github.com/cnpm/npminstall/issues/386
=> 📦 NEW: Support libc field on conditions install

lib/download/npm.js, lib/install.js, lib/utils.js, package.json, test/utils.test.js
Ignore libc check if libc family is null
=> 🐛 FIX: Use detect-libc to get libc family

package.json
closes https://github.com/cnpm/npminstall/issues/384
=> feat: upgrade node-gyp@8 to support python3

.github/workflows/ci.yml, README.md, package.json, test/fixtures/install-raw-socket/package.json, test/get.test.js, test/install-with-python3.test.js
pick from https://github.com/cnpm/npminstall/pull/385
closes https://github.com/cnpm/npminstall/issues/384
=> feat: upgrade node-gyp@9 to support python3

lib/download/npm.js, test/fix-bug-versions.test.js
Deps https://github.com/cnpm/bug-versions/pull/185
=> 📦 NEW: Support override custom scripts on bug-versions

bin/install.js, test/installSaveDeps.test.js
https://github.com/npm/rfcs/pull/547
=> feat: save dep with tag if install with tag

lib/download/local.js
* fix: fix parallel install from local directory (#398)
* fix: parallel install from local directory
Co-authored-by: Yiyu He <dead_horse@qq.com>
=> fix: pick fix parallel install from local directory (#398)

bin/install.js, package.json, test/fixtures/rootpath/pkg/index.js, test/rootpath.test.js
https://github.com/vercel/turbo/issues/485
=> fix: auto set INIT_CWD env on install scripts

bin/install.js, lib/lifecycle_scripts.js, lib/utils.js, test/fixtures/postinstall/package.json, test/postinstall.test.js, test/runscript.test.js
closes https://github.com/cnpm/npminstall/issues/458
=> feat: run scripts on background by default

bin/install.js, test/fixtures/lockfile/package-lock.json, test/fixtures/lockfile/package.json, test/install-with-lockfile.test.js, test/installGlobal.test.js
Add the `ignoreOptionalDependencies` parameter to fix the npe with optionalDeps packages during lockfile conversion.
=> fix: npe in lockfileConvertor

bin/install.js, test/fixtures/lockfile/package-lock.json, test/fixtures/lockfile/package.json, test/install-with-lockfile.test.js
=> fix: lockfile convert option

bin/install.js, test/install-cache-strict.test.js
npminstall 内置了 tarball 的缓存能力，默认的缓存地址为 `~/.npminstall_tarball`.   npminstall 不支持通过 `--cache` 配置缓存目录的位置，但支持通过 `process.env.npm_config_cache` 进行配置。
预期能通过配置文件或环境变量修改 npminstall 缓存的位置，且缓存的目录能与 npm 区分开
如果使用 `npm_config_cache` 配置 npminstall 的缓存位置，会同时修改 npm 的缓存位置，导致两个缓存总是位于同一个父目录
新增 `process.env.npminstall_cache` 配置，允许配置缓存位置，且能够和 npm 的缓存目录分隔开。  (或者其他方式，能满足需求即可）
=> feat: add support for process.env.npminstall_cache

bin/install.js, test/install-cache-strict.test.js
=> feat: add support for process.env.npminstall_cache (cherry-pick #471)
