cnpm/npminstall

- lib/download.js
> refactor: tzgfile do not store on dist

- .travis.yml
- README.md
- appveyor.yml
- lib/bin.js
- lib/index.js
- lib/install.js
- lib/link.js
- lib/utils.js
- package.json
- test/all.js
- test/bundleDependencies.test.js
- test/fixtures/postinstall/package.json
- test/fixtures/postinstall/preinstall.sh
- test/fixtures/runscript/package.json
- test/index.test.js
- test/postinstall.test.js
- test/runscript.test.js
> feat: runScript support Windows

- lib/index.js
- lib/install.js
- package.json
- test/bigPackage.test.js
- test/fixtures/peerDependencies/package.json
- test/fixtures/spmtest/package.json
- test/fixtures/spmwebpacktest/package.json
- test/peerDependencies.test.js
validate peer deps on parentDir
> feat: add peerDependencies validate

- .travis.yml
- README.md
- appveyor.yml
- lib/dependencies.js
- lib/download.js
- lib/index.js
- lib/install.js
- lib/utils.js
- package.json
- test/bigPackage.test.js
- test/fixtures/link-latest-version/package.json
- test/fixtures/optional/package.json
- test/fixtures/production/package.json
- test/fixtures/standardtest/index.js
- test/fixtures/standardtest/package.json
- test/git.sh
- test/index.test.js
- test/link-latest-version.test.js
- test/optionalDependencies.test.js
> feat: link every module latest version to .npminstall/node_modules

- .gitignore
- lib/config.js
- lib/download.js
- lib/get.js
- lib/index.js
- lib/install.js
- package.json
- test/download.test.js
- test/git.sh
also destroy response stream when status is not 200
> feat: add download speed

- bin/install.js
- lib/get.js
- lib/index.js
- lib/install.js
- test/cleanup.test.js
- feat: support process.env.NODE_ENV and add --version command
> fix: only remove done file when install error

- README.md
- benchmark/Makefile
- bin/install.js
- lib/config.js
- lib/download.js
- lib/get.js
- lib/index.js
- lib/install.js
- package.json
- test/download.test.js
```bash
-------npminstall-------
All packages installed (429 packages, use 13s, speed 908.75kB/s, json 2.98MB, tarball 8.95MB)
real	0m13.805s
user	0m10.060s
sys	0m4.956s
-------npminstall with cache-------
All packages installed (429 packages, use 12s, speed 254.89kB/s, json 2.98MB, tarball 0B)
real	0m12.285s
user	0m9.077s
sys	0m4.443s
-------npminstall --no-cache-------
All packages installed (429 packages, use 13s, speed 919.24kB/s, json 2.99MB, tarball 8.95MB)
real	0m13.583s
user	0m9.579s
sys	0m4.423s
---------pnpm-----------
real	0m16.323s
user	0m13.132s
sys	0m5.014s
----------npm-----------
real	0m45.721s
user	0m31.606s
sys	0m9.842s
----npm with cache------
real	0m30.427s
user	0m26.670s
sys	0m7.821s
```
> feat: add local cache dir to store tarball files

- README.md
- bin/install.js
- lib/bin.js
- lib/index.js
- lib/install.js
- test/installTarget.test.js
> specific install directory

- .travis.yml
- appveyor.yml
- bin/install.js
- package.json
- test/installSaveDeps.test.js
> feat(bin): support --save, --save-dev and --save-optional

- bin/install.js
- lib/index.js
- lib/utils.js
- package.json
- test/fixtures/auto-set-npm-env/package.json
- test/fixtures/auto-set-npm-env/postinstall.js
- test/postinstall.test.js
npminstall --foo=bar will set `npm_foo=bar` env
> fix: auto set npm env just like npm cli does

- bin/install.js
> fix: use registry.npmjs.com by default on bin/install.js

- lib/download/npm.js
- lib/install.js
fixes #30, #31 
make sure package install completed when read from cache
> fix: wait package install completed

- README.md
- bin/install.js
- lib/download/npm.js
- lib/download/remote.js
- lib/get.js
> feat: support read strict-ssl from npm config

- README.md
- benchmark/Makefile
- bin/install.js
- lib/index.js
- lib/prepublish.js
- package.json
- test/fixtures/postinstall/package.json
- test/git.sh
- test/installLocal.test.js
- test/postinstall.test.js
- test: add pnpm benchmark scripts
- feat: support npm_china env
> fix: add prepublish script after postinstall

- bin/install.js
> fix: support shortcut install options

- README.md
- lib/download/git.js
- lib/download/npm.js
- lib/download/remote.js
- lib/utils.js
- package.json
- test/fixtures/packageMeta/package.json
- test/index.test.js
> fix: add _from, _resolved back to package.json

- .gitignore
- lib/download/git.js
- lib/download/remote.js
- lib/utils.js
- test/installGit.test.js
> Can install from a revision hash now.

- bin/install.js
closes #55
closes https://github.com/cnpm/cnpm/issues/97
> fix: fix global path on windows

- bin/install.js
- test/installSaveDeps.test.js
> feat: sort pkg.dependencies

- lib/download/git.js
- lib/download/local.js
- lib/download/remote.js
- lib/install.js
- lib/utils.js
- test/all.js
> fix: trim string before json parse it

- bin/install.js
- lib/download/npm.js
- lib/get.js
- package.json
> fix: get bianry mirror package

- bin/install.js
> fix: add retry to get binary-mirror-config/latest

- .travis.yml
- appveyor.yml
- bin/install.js
- lib/config.js
- lib/install.js
- lib/local_install.js
- lib/utils.js
- test/bundleDependencies.test.js
- test/fixtures/specify-darwin-os/index.js
- test/fixtures/specify-darwin-os/package.json
- test/fixtures/specify-linux-os/index.js
- test/fixtures/specify-linux-os/package.json
- test/npminstall.js
- test/specify-os-property.test.js
> feat: support package.json#os property

- lib/install.js
- lib/utils.js
- test/utils.test.js
UnSupportedPlatformError only show error message on optional deps
closes cnpm/cnpm#103
> fix: anti os match bug

- lib/download/npm.js
- lib/get.js
- lib/local_install.js
- lib/utils.js
- test/bundleDependencies.test.js
- test/download.test.js
- test/fixtures/github/package.json
- test/fixtures/packageMeta/package.json
- test/index.test.js
- test/installGlobal.test.js
- test/installRemote.test.js
closes https://github.com/cnpm/cnpm/issues/114
> feat: retry 3 times on shasum not match and 50x error

- README.md
- bin/install.js
- lib/install.js
- test/license.test.js
> fix: forbidden licenses just show tips

- lib/config.js
- lib/download/npm.js
- test/flow-bin.test.js
https://github.com/cnpm/cnpm/issues/117
> feat: support flow-bin mirror

- bin/install.js
- test/npm_execpath_env.test.js
> fix: add npm_execpath env in pre/post install script

- lib/install.js
- lib/local_install.js
- test/cleanup.test.js
- test/fixtures/postinstall-error/package.json
> fix: remove done file when install failed

- lib/local_install.js
- test/index.test.js
> feat: fetch from regsitry when not install from package.json

- README.md
- bin/uninstall.js
- lib/postuninstall.js
- lib/preuninstall.js
- lib/uninstall.js
- package.json
- test/fixtures/uninstall/package.json.template
- test/fixtures/uninstall/pkg/index.js
- test/fixtures/uninstall/pkg/package.json
- test/flow-bin.test.js
- test/uninstall.test.js
> feat: support uninstall

- README.md
- appveyor.yml
- lib/local_install.js
- lib/uninstall.js
- lib/utils.js
- test/bundleDependencies.test.js
- test/cleanup.test.js
- test/download.test.js
- test/ignoreScripts.test.js
- test/index.test.js
- test/installLocal.test.js
- test/installRemote.test.js
- test/installTarget.test.js
- test/linkLatestVersion.test.js
- test/linkRoot.test.js
- test/postinstall.test.js
- test/runscript.test.js
- test/uninstall.test.js
> refactor: remove .npminstall

- bin/install.js
- lib/download/npm.js
- package.json
- test/bin.test.js
- test/bundleDependencies.test.js
- test/cleanup.test.js
- test/download.test.js
- test/forceSymlink.test.js
- test/ignoreScripts.test.js
- test/index.test.js
- test/installGit.test.js
- test/installGlobal.test.js
- test/installLocal.test.js
- test/installRemote.test.js
- test/installSaveDeps.test.js
- test/installTarget.test.js
- test/link.test.js
- test/linkLatestVersion.test.js
- test/linkRoot.test.js
- test/node-gyp.test.js
- test/npm_execpath_env.test.js
- test/optionalDependencies.test.js
- test/postInstallError.test.js
- test/postinstall.test.js
- test/production.test.js
- test/runscript.test.js
- test/specify-os-property.test.js
- test/uninstall.test.js
- test/utils.test.js
- show tarball file path when shasum error
- show version and process args when install error
> fix: improve install error message tips

- lib/utils.js
- test/bundleDependencies.test.js
- test/cleanup.test.js
- test/download.test.js
- test/eslint-plugin-html.test.js
- test/fixtures/eslint-plugin-html/.eslintrc.js
- test/fixtures/eslint-plugin-html/index.js
- test/fixtures/eslint-plugin-html/package.json
- test/ignoreScripts.test.js
- test/index.test.js
- test/installRemote.test.js
- test/uninstall.test.js
closes https://github.com/cnpm/cnpm/issues/133#issuecomment-236926965
> fix: store dir name should ends with name

- bin/install.js
- lib/download/npm.js
- lib/local_install.js
- package.json
- test/bin.test.js
- test/download.test.js
- test/semver_install.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/111)
> feat: should follow npm install version

- bin/install.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/114)
> fix: auto add EOL on --save

- lib/download/git.js
- package.json
closes #107 #108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/117)
> fix: use normalize-git-url to parse git url

- lib/download/npm.js
- test/installScope.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/118)
> fix: npm registry scoped permission error

- lib/utils.js
- test/all.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/120)
> fix: fix package.json permission

- lib/get.js
https://travis-ci.org/eggjs/egg-view-nunjucks/jobs/160791554#L328
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/125)
> fix: globalOptions.console undefined

- .travis.yml
- bin/install.js
- test/fixtures/postinstall/index.js
- test/git-clone-install.sh
- test/postinstall.test.js
closes https://github.com/cnpm/npminstall/issues/121
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/126)
> fix: add missing npm_config_argv env

- lib/download/npm.js
- test/node-pre-gyp.test.js
- test/npminstall.js
ignore node-pre-gyp http protocol checker
> fix: binary mirror could be http protocol

- lib/dependencies.js
- lib/download/npm.js
- lib/local_install.js
- lib/utils.js
- test/fixtures/install-pedding/package.json
- test/git-clone-install.sh
- test/install-pedding.test.js
- fix: try to fill empty version from local deps
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/129)
> feat: use npminstall instead of npm install on runscript

- bin/uninstall.js
- lib/uninstall.js
- test/uninstallGlobal.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/130)
> fix: support uninstall -g

- lib/install.js
- lib/local_install.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/134)
> feat: show deprecate message after install step

- lib/install.js
- lib/local_install.js
> better log interface for recently updated list

- .travis.yml
- appveyor.yml
- bin/install.js
- lib/get.js
- lib/local_install.js
- package.json
- test/flow-bin.test.js
closes https://github.com/cnpm/npminstall/issues/152
> fix: limit max 10 sockets per host

- .travis.yml
- appveyor.yml
- lib/download/npm.js
- lib/utils.js
- package.json
- test/fixtures/gulp-imagemin/package.json
- test/gulp-imagemin.test.js
closes https://github.com/cnpm/mirrors/issues/114
> feat: support raw.github.com mirror

- bin/install.js
- lib/config.js
- lib/download/npm.js
- lib/install.js
- package.json
- test/npminstall.js
closes https://github.com/cnpm/npminstall/issues/157
> refactor: use ENVS from binary-mirror-config

- bin/install.js
- test/fixtures/rootpath/package.json
- test/fixtures/rootpath/pkg/index.js
- test/fixtures/rootpath/pkg/package.json
- test/rootpath.test.js
> feat: add npm_rootpath to env

- bin/install.js
- lib/download/git.js
- lib/download/local.js
- lib/download/npm.js
- lib/download/remote.js
- lib/install.js
- lib/local_install.js
- test/installGit.test.js
- test/installRemote.test.js
- test/installSaveDeps.test.js
> fix: install package from git/remote/hosted with save options

- bin/install.js
- test/download.test.js
- test/fixtures/github/package.json
- test/production.test.js
And show warning message when node_modules exists
> fix: should force set detail on production mode

- bin/install.js
- lib/download/npm.js
- lib/format_install_options.js
- lib/global_install.js
- lib/local_install.js
- lib/utils.js
- test/installGlobal.test.js
closes https://github.com/cnpm/npminstall/issues/166
> refactor: global install root dir don't use link

- lib/get.js
- test/fixtures/packageMeta/package.json
- test/get.test.js
- test/index.test.js
closes https://github.com/cnpm/npminstall/issues/173
> feat: should get with retry on all error scene

- bin/install.js
- lib/bin.js
- lib/download/git.js
- lib/download/local.js
- lib/download/remote.js
- lib/install.js
- lib/local_install.js
- lib/preinstall.js
- lib/utils.js
- test/production.test.js
> feat: more debug info

- lib/get.js
- lib/utils.js
- test/installSaveDeps.test.js
closes https://github.com/cnpm/cnpm/issues/174
> fix: don't retry to get mirror latest package

- lib/local_install.js
- test/bundleDependencies.test.js
- test/ignoreScripts.test.js
- test/index.test.js
- test/installRemote.test.js
Add linkTask parallel limit to 20
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/185)
> feat: add .npminstall.done file on node_modules after install success

- lib/format_install_options.js
- lib/install.js
- lib/local_install.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/186)
> feat: add install and link tasks progresses

- lib/download/npm.js
- test/index.test.js
closes https://github.com/cnpm/npminstall/issues/188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/189)
> fix: auto fix invaild tgz file

- README.md
- appveyor.yml
- lib/download/npm.js
- lib/local_install.js
- package.json
- test/concurrency-install.test.js
- test/fixtures/concurrency1/package.json
- test/fixtures/concurrency2/package.json
- test/installLocal.test.js
closes https://github.com/cnpm/npminstall/issues/176  and https://github.com/cnpm/npminstall/issues/184
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/190)
> feat: support parallel execution

- bin/install.js
- lib/format_install_options.js
- lib/local_install.js
- test/bigPackage.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/194)
> feat: enable cpu and memory usage traces by --trace

- README.md
- bin/install.js
- lib/install.js
- test/engine-strict.test.js
closes https://github.com/cnpm/npminstall/issues/156
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/195)
> feat: support engines.node version checker

- lib/install.js
- test/fixtures/flatten/mod5/package.json
- test/fixtures/flatten/mod6/package.json
- test/fixtures/flatten/mod7/package.json
- test/flatten.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/198)
> Fix flatten

- README.md
- lib/install.js
- lib/utils.js
- test/fixtures/flatten/mod10/package.json
- test/fixtures/flatten/mod8/package.json
- test/fixtures/flatten/mod9/package.json
- test/flatten.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/200)
> feat: n.x and n.m.x always use flatten

- lib/download/npm.js
https://github.com/strongloop/fsevents/commit/ca07cfdb534f6f85a4a918bc99ef414d191275dc
> fix: support fsevents mirror

- lib/install.js
- test/fixtures/types/package.json
- test/flatten-types.test.js
- test/flatten.test.js
closes #204 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/206)
> feat: typescript definitions always flatten

- .gitignore
- lib/install.js
- test/fixtures/peer/package.json
- test/peer.test.js
closes #205 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/207)
> feat: improve peerDependencies' lookup

- lib/install.js
- test/peer.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/209)
> fix: peer dependency duplicated with dependency

- lib/format_install_options.js
- lib/install.js
- lib/local_install.js
- test/all.js
- test/fixtures/react-and-react-dom/package.json
- test/peer.test.js
closes #211
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/212)
> fix: ensure peer dependencies flatten

- test/all.js
- test/git-clone-install.sh
- test/git.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/213)
> test: remove ghost install test

- lib/format_install_options.js
- lib/install.js
- lib/local_install.js
- test/fixtures/package-versions/package.json
- test/ignoreScripts.test.js
- test/installRemote.test.js
- test/package-versions.test.js
closes #215 
看第二个 commit 才是新增的
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/216)
> Record versions

- lib/utils.js
- test/bundleDependencies.test.js
- test/cleanup.test.js
- test/ignoreScripts.test.js
- test/index.test.js
- test/installRemote.test.js
- test/uninstall.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/220)
> feat: store path starts with name

- lib/utils.js
- test/bundleDependencies.test.js
- test/cleanup.test.js
- test/ignoreScripts.test.js
- test/index.test.js
- test/installRemote.test.js
- test/next.test.js
- test/postInstallError.test.js
- test/uninstall.test.js
closes https://github.com/cnpm/cnpm/issues/194
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/227)
> fix: remove starting dot to ensure webpack2 work

- lib/install.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/228)
> feat: recently update display latest version

- README.md
- bin/install.js
- lib/format_install_options.js
- test/install-cache-strict.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/230)
> feat: enable disk cache strict event on production env

- lib/format_install_options.js
- package.json
Fix #233
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/234)
> Refactor rename await

- .travis.yml
- lib/download/git.js
- test/all.js
- test/installGit.test.js
pick from #238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/240)
> Fix git install error 2.x

- .travis.yml
- lib/download/git.js
- test/all.js
- test/installGit.test.js
closes #237 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/238)
> fix: warning when package name unmatch from git

- bin/install.js
- lib/get.js
- package.json
- test/fixtures/reverse-proxy.js
- test/proxy.test.js
npm_config_proxy and npm_proxy env also work!
closes https://github.com/cnpm/npminstall/issues/135
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/242)
> feat: support --proxy

- README.md
- benchmark/Makefile
- test/git.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/244)
> chore: update pnpm links

- .travis.yml
- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/246)
> test: don't clean cache on windows

- lib/download/npm.js
e.g.: utf-8-validate
https://github.com/cnpm/mirrors/issues/162
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/250)
> feat: support mirror prebuild-install package

- lib/install.js
- lib/utils.js
- test/fixtures/same-bin-name/package.json
- test/install-save-bin-name.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/251)
> fix: handle concurrent install same bin name error

- .travis.yml
- appveyor.yml
- lib/download/npm.js
- lib/utils.js
- test/bundleDependencies.test.js
- test/utils.test.js
closes https://github.com/cnpm/npminstall/issues/261
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/264)
> feat: support latest-{major} tag as latest version

- .travis.yml
- LICENSE.txt
- appveyor.yml
- lib/download/npm.js
- test/fix-bug-versions.test.js
- test/fmode.test.js
- test/install-cache-strict.test.js
- test/install-save-folder.test.js
- test/next.test.js
- test/node-pre-gyp.test.js
base on https://github.com/cnpm/bug-versions/pull/8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cnpm/npminstall/266)
> feat: support auto fix bug dependencies

- lib/download/npm.js
- lib/utils.js
options.registry = 'https://registry.my.com?foo=bar'
> fix: should keep querystring on registry url

- lib/download/npm.js
- lib/utils.js
- test/download.test.js
- test/utils.test.js
relate to https://github.com/cnpm/cnpmjs.org/pull/1344
> feat: support download tarball from other_urls query params

- lib/download/npm.js
- test/fixtures/install-cypress/package.json
- test/install-cypress.test.js
closes https://github.com/cnpm/mirrors/issues/181
> feat: download cypress from mirrors

- bin/install.js
- lib/download/npm.js
- lib/format_install_options.js
- lib/local_install.js
- package.json
- test/fixtures/install-enable-prune/package.json
- test/install-enable-prune.test.js
closes https://github.com/cnpm/npminstall/issues/272
> feat: enable prune unused files by --prune option

- lib/download/npm.js
https://unpkg.com/antd-tools@5.1.6/lib/gulpfile.js
> fix: don't remove gulpfile

- lib/download/npm.js
- lib/utils.js
- package.json
- test/fixtures/install-vscode/package.json
- test/install-cypress.test.js
- test/install-vscode.test.js
deps on https://github.com/cnpm/binary-mirror-config/pull/7
> feat: replace vscode raw.gitcontent.com url

- README.md
- bin/install.js
The word `chinese` is misspelled. fix it.
> fix cacography: chinses -> chinese

- lib/local_install.js
- test/local-install-pkgs.test.js
revert https://github.com/cnpm/npminstall/pull/282/files#diff-fcb03c95bc3ad63da4b4490a731316fbR150 changed
> fix: try to link latest version to top node_modules

- lib/download/npm.js
- package.json
like sharp package
detail see https://github.com/cnpm/binary-mirror-config/pull/10
> feat: support binary mirror replaceHostFiles config

- lib/local_install.js
- test/fixtures/sub-module-optional-dep-install-fails/package.json
- test/ignore-install-optional-deps-fails.test.js
```bash
[npminstall:runscript:error] nunjucks@3.1.6 › chokidar@2.0.4 › fsevents@^1.2.2 scripts.install run "node install" error: Error: Run "sh -c node install" error, exit code 1
nunjucks@3.1.6 › chokidar@2.0.4 › fsevents@^1.2.2 optional error: Error: Run "sh -c node install" error, exit code 1
at ChildProcess.proc.on.code (/Users/mk2/git/github.com/cnpm/npminstall/node_modules/_runscript@1.3.0@runscript/index.js:74:21)
at ChildProcess.emit (events.js:182:13)
at maybeClose (internal/child_process.js:978:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```
> feat: show post isntall scripts error detail message

- lib/download/npm.js
from https://cdn.cypress.io/desktop/
> feat: try to use cypress new platforms

- lib/download/npm.js
from https://cdn.cypress.io/desktop/
> feat: try to use cypress new platforms (#307)

- .gitignore
- bin/install.js
- lib/get.js
- lib/local_install.js
- test/fixtures/optional-dep-postinstall/package.json
- test/linkLatestVersion.test.js
- test/postInstallError.test.js
`--force-link-latest` mode will link the latest version to node_modules even the link already exists.
> feat: add force-link-latest mode

- .travis.yml
- test/postinstall.test.js
- test/proxy.test.js
> test: add node 13

- lib/download/npm.js
- test/all.js
- test/fixtures/scope/.cnpmrc
- test/helper.js
- test/installScopeRegistry.test.js
pick from https://github.com/cnpm/npminstall/pull/306
> feat: support custom scope registry

- lib/bin.js
- package.json
- test/fixtures/runscript-with-egg-doctools/package.json
- test/runscript-with-egg-doctools.test.js
need to wait for https://github.com/npm/cmd-shim/pull/42
to be merged and publish a new version.
closes https://github.com/cnpm/npminstall/issues/316
> fix: dont add quotes on node global bin path on Windows

- lib/bin.js
- package.json
- test/normalize-bin.test.js
https://blog.npmjs.org/post/189618601100/binary-planting-with-the-npm-cli
> fix: the vulnerabilities same as npm cli

- lib/format_install_options.js
- test/fixtures/install-husky-4/index.js
- test/fixtures/install-husky-4/package.json
- test/install-with-env.test.js
closes https://github.com/cnpm/cnpm/issues/317
> feat: support INIT_CWD env

- lib/local_install.js
- lib/prepare.js
- test/fixtures/postinstall/package.json
- test/postinstall.test.js
see https://docs.npmjs.com/misc/scripts#prepublish-and-prepare
> feat: support script.prepare

- bin/install.js
- test/install-cache-strict.test.js
```bash
npm_config_cache=/oss/cache/.npminstall npminstall koa
```
> feat: support npm_config_cache to change default cache dir

- bin/install.js
- lib/download/index.js
- lib/download/npm.js
- lib/npa_types.js
- test/installSaveDeps.test.js
```bash
npminstall -S lodash-has-v3@npm:lodash@^3 lodash-has-v3@npm:lodash@^4
```
should save package to package.json and be installed.
> fix: fix save alias error

- lib/download/npm.js
- lib/install.js
- lib/utils.js
- test/download.mockArchScript.js
- test/download.test.js
- test/install-ignore-optional.test.js
- test/utils.test.js
not only platform, should check arch too
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#cpu
> fix: should check cpu on process.arch too

- package.json
> fix: upgrade node-gyp from ^3 to ^6

- package.json
https://github.com/cnpm/npminstall/pull/373
> fix: use ora 4.0.5 to support node 8

- .github/workflows/ci.yml
- lib/download/npm.js
- test/fix-bug-versions.test.js
Deps https://github.com/cnpm/bug-versions/pull/185
pick from https://github.com/cnpm/npminstall/pull/393
> 📦 NEW: Support override custom scripts on bug-versions (#393)

- README.md
- bin/install.js
- lib/download/npm.js
- lib/install_package.js
- lib/local_install.js
* fix some grammatical errors in README.
* add some explanation during installation procedure.
> doc: add some reading comments and typo fixes.

- lib/install_package.js
closes https://github.com/cnpm/npminstall/issues/445
> fix: ignore anti semver tips on `<name>@*` deps

- lib/bin.js
- lib/install_package.js
- test/bin.test.js
> fix: show warn message when bin file not exists

- lib/local_install.js
- test/fixtures/npm-workspaces/packages/b/package.json
- test/install-workspaces.test.js
make sure eslint plugin mode works
> fix: link public hoist package to `<workspaceRoot>/node_modules`

- lib/lifecycle_scripts.js
fix: https://github.com/cnpm/cnpm/issues/407
> fix: should not run prepare in a production or global package

- bin/install.js
- lib/download/npm.js
- lib/local_install.js
- test/fixtures/install-offline/index.js
- test/fixtures/install-offline/package.json
- test/install-offline.test.js
closes https://github.com/cnpm/npminstall/issues/456
> feat: support offline mode

- .gitignore
- bin/install.js
- lib/download/npm.js
- lib/lockfile_resolver.js
- test/fixtures/lockfile/package-lock.json
- test/fixtures/lockfile/package.json
- test/install-with-lockfile.test.js
> feat: add npm package-lock.json support for 6.x
